/** @type {import('tailwindcss').Config} */
export default {
  safelist: [
    "text-blue-400",
    "text-blue-200",
    "hover:text-blue-200",
    "text-center",
    "bg-black",
    "bg-black/70",
    "bg-black-80",
    "text-white",
    "h-full",
    "h-[100svh]",
    "bg-violet-600",
    "bg-violet-600/80",
    "hover:bg-violet-600/80",
    "w-[100px]",
    "w-[150px]",
    "w-[200px]",
    "h-[300px]",
    "hover:bg-black/80",
    "sm:w-[200px]",
    "sm:h-[300px]",
    "flex",
    "flex-auto",
    "text-start",
    "p-2",
    "pl-2",
    "px-2",
    "py-2",
    "hover:bg-white/20",
    "bg-white/20",
    "styled-scrollbar",
    "text-emerald-400",
    "bg-blue-100",
  ],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  plugins: [],
};
